import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/organisms/Header";
import { readUtilUser } from "./actions/user/read";
import { AuthProvider } from "@/contexts/AuthContext"; // ★ AuthProvider をインポート

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "hadbit-app",
  description: "Generated by 2025 syunjyu gmail.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const user = await readUtilUser();
  // console.log("RootLayout", user);
  return (
    <html lang="ja">
      {/* 日本語なら lang="ja" */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`} // flex flex-col min-h-screen を追加してフッターを下に固定しやすくする
      >
        <AuthProvider>
          {" "}
          {/* ★ AuthProvider でラップ */}
          <Header /> {/* ヘッダーコンポーネントをここに追加 */}
          <main className="flex-grow container mx-auto px-4 py-8">
            {/* メインコンテンツ用のラッパーを追加 (任意) */}
            {children}
          </main>
          {/* 必要であればフッターをここに追加 */}
          {/* <footer className="border-t py-4 text-center text-sm text-muted-foreground">
          © 2025 Hadbit
        </footer> */}
        </AuthProvider>
      </body>
    </html>
  );
}
